### ISSUE TITLE
Outstanding Ubuntu updates

### ISSUE THREAD

**Issue by aussielunix** [bvilnis/terraform-aws-code-server#1]
When I provision a new instance
And I ssh in for the first time
I am presented with the following information
```
74 packages can be updated.
36 updates are security updates.
```
https://github.com/benny-v/linux-cloudstation/blob/master/digitalocean/user_data.sh#L13
Consider changing this to `apt full-upgrade`

**Comment by bvilnis** [comment]
Issue fixed as part of minor script refactoring in regards to `user_data.sh`
